# Generated by Django 5.1.6 on 2025-08-08 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_proposal_admin_comment_proposal_admin_validation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('gateway_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('mpesa', 'M-Pesa'), ('crypto', 'Cryptomonnaie')], max_length=20, verbose_name='Type de passerelle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('test', 'Mode test')], default='test', max_length=20, verbose_name='Statut')),
                ('api_key', models.CharField(max_length=255, verbose_name='Clé API')),
                ('secret_key', models.CharField(max_length=255, verbose_name='Clé secrète')),
                ('webhook_url', models.URLField(blank=True, verbose_name='URL webhook')),
                ('supported_currencies', models.JSONField(default=list, verbose_name='Devises supportées')),
                ('supported_countries', models.JSONField(default=list, verbose_name='Pays supportés')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Frais (%)')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais fixes')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant maximum')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Passerelle de paiement',
                'verbose_name_plural': 'Passerelles de paiement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('payment_type', models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('crypto', 'Cryptomonnaie'), ('cash', 'Espèces'), ('check', 'Chèque')], max_length=20, verbose_name='Type de paiement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='ri-bank-card-line', max_length=50, verbose_name='Icône')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('maintenance', 'En maintenance')], default='active', max_length=20, verbose_name='Statut')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Frais de traitement (%)')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant maximum')),
                ('supported_countries', models.JSONField(default=list, verbose_name='Pays supportés')),
                ('api_config', models.JSONField(default=dict, verbose_name='Configuration API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(default=dict, verbose_name='Réponse de la passerelle'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de traitement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('crypto', 'Cryptomonnaie'), ('cash', 'Espèces'), ('check', 'Chèque')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_type', models.CharField(choices=[('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('litecoin', 'Litecoin (LTC)'), ('bitcoin_cash', 'Bitcoin Cash (BCH)'), ('ripple', 'Ripple (XRP)'), ('cardano', 'Cardano (ADA)'), ('polkadot', 'Polkadot (DOT)'), ('chainlink', 'Chainlink (LINK)'), ('stellar', 'Stellar (XLM)'), ('usdt', 'Tether (USDT)'), ('usdc', 'USD Coin (USDC)'), ('dai', 'Dai (DAI)')], max_length=20, verbose_name='Type de crypto')),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Montant en crypto')),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Taux de change')),
                ('wallet_address', models.CharField(max_length=100, verbose_name='Adresse de portefeuille')),
                ('transaction_hash', models.CharField(blank=True, max_length=100, verbose_name='Hash de transaction')),
                ('block_height', models.IntegerField(blank=True, null=True, verbose_name='Hauteur de bloc')),
                ('confirmations', models.IntegerField(default=0, verbose_name='Confirmations')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué'), ('expired', 'Expiré')], default='pending', max_length=20, verbose_name='Statut')),
                ('expires_at', models.DateTimeField(verbose_name='Expire à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Paiement crypto',
                'verbose_name_plural': 'Paiements crypto',
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa (Kenya)'), ('airtel_money', 'Airtel Money'), ('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('vodafone_cash', 'Vodafone Cash'), ('tigo_pesa', 'Tigo Pesa'), ('ecocash', 'EcoCash (Zimbabwe)'), ('mobikwik', 'MobiKwik (Inde)'), ('paytm', 'Paytm (Inde)'), ('phonepe', 'PhonePe (Inde)'), ('gpay', 'Google Pay'), ('apple_pay', 'Apple Pay')], max_length=20, verbose_name='Fournisseur')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transaction')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Paiement Mobile Money',
                'verbose_name_plural': 'Paiements Mobile Money',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.paymentgateway', verbose_name='Passerelle de paiement'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('transaction_type', models.CharField(choices=[('payment', 'Paiement'), ('refund', 'Remboursement'), ('chargeback', 'Contestation'), ('fee', 'Frais'), ('adjustment', 'Ajustement')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='Réponse de la passerelle')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=100, verbose_name='ID commande PayPal')),
                ('paypal_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID paiement PayPal')),
                ('payer_id', models.CharField(blank=True, max_length=100, verbose_name='ID payeur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Paiement PayPal',
                'verbose_name_plural': 'Paiements PayPal',
            },
        ),
    ]
